## Insert 1 to 100 numbers in a numpy array and reshape it to 10*10 matrix.


In [17]:
import numpy as np
np.random.seed(8)
arr=np.random.randint(1,100,100)
print(arr)
arr1=arr.reshape((10,10))
print("after reshape\n",arr1)

[68 85  6 91  9 84 64 49 86 61 50 75 28 14 10 62 16 94 99 60 19 15 94 57
 10 52 69 54 54 72 60 43 27 67 10 82 16 93 92 64 87 32 21 46 22 73 93 29
 96 48 11 65  8 46  3 39 72 96 37 90 61 92 69 38 67 83 39 55 87 40 47  7
 96 33 74 99  8 10 99 43 20 60 49 10 17 79 56 56 21 99 88 99 25  7 29  6
 67 20 76 12]
after reshape
 [[68 85  6 91  9 84 64 49 86 61]
 [50 75 28 14 10 62 16 94 99 60]
 [19 15 94 57 10 52 69 54 54 72]
 [60 43 27 67 10 82 16 93 92 64]
 [87 32 21 46 22 73 93 29 96 48]
 [11 65  8 46  3 39 72 96 37 90]
 [61 92 69 38 67 83 39 55 87 40]
 [47  7 96 33 74 99  8 10 99 43]
 [20 60 49 10 17 79 56 56 21 99]
 [88 99 25  7 29  6 67 20 76 12]]
